name: Node.js CI

on: [push]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
      - uses: actions/checkout@main

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - run: yarn install

      - run: yarn type-check

      - run: yarn lint

      - run: yarn build
